"$schema" = "https://starship.rs/config-schema.json"

format = """
$directory\
$git_branch\
$git_status\
$kubernetes\
$terraform\
$python\
$golang\
$nodejs\
$cmd_duration\
$line_break\
$character"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[kubernetes]
disabled = false
format = "[$symbol$context(/$namespace)]($style) "
symbol = "☸ "

[terraform]
format = "[$symbol$workspace]($style) "

[python]
format = "[${symbol}${version}]($style) "
symbol = " "

[golang]
format = "[$symbol$version]($style) "
symbol = " "

[nodejs]
format = "[$symbol$version]($style) "
symbol = " "

[cmd_duration]
min_time = 2_000
format = "[$duration]($style) "
